name: peerpulse
description: Private 5-person class recording app.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2 # This "remembers" the user's name
